version: 3

tasks:
  docs:
    cmd: sphinx-autobuild docs/ docs/_build/ --watch rtorrent_rpc --port 8920

  minor:
    cmds:
      - pyproject-bump minor
      - task: bump

  patch:
    cmds:
      - pyproject-bump micro
      - task: bump

  bump:
    vars:
      VERSION:
        sh: tq --raw 'project.version' -f pyproject.toml
    cmds:
      - uv sync
      - git add pyproject.toml uv.lock
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -a -m "v{{.VERSION}}"'
