name: Build wheel

on:
  workflow_call:

jobs:
  build:
    name: Build pure Python wheel
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v8.2.0

      - run: uv build

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-pure-py
          path: dist/*.whl
