name: Build wheel

on:
  workflow_call:

jobs:
  build:
    name: Build pure Python wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: pipx run build

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-pure-py
          path: dist/*.whl
