name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/_build_wheels.yaml

  pypi:
    name: Upload wheels to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - run: pipx run twine upload dist/* --disable-progress-bar
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
