name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/_build_wheels.yaml

  pypi:
    name: Upload wheels to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - uses: astral-sh/setup-uv@v9.0.0

      - run: uv build
      - run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
