name: tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build_wheels.yaml

  twine-check:
    name: Check dist
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - run: pipx run twine check --strict dist/*

  test-cp:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-24.04'
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v8.2.0
        with:
          activate-environment: true

      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - run: uv sync --no-install-project --group=dev

      - run: uv pip install ./dist/*.whl

      - run: uv run pytest

  test-pass:
    needs:
      - test-cp
      - twine-check
    runs-on: 'ubuntu-latest'
    steps:
      - run: 'echo success'
